# Generated by Django 4.2.1 on 2023-05-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password1", models.CharField(max_length=30)),
                ("password2", models.CharField(max_length=30)),
            ],
        ),
    ]
