# Generated by Django 4.2.1 on 2023-06-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="authorname",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
