# Generated by Django 4.2.1 on 2023-05-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileupload",
            old_name="imgfile",
            new_name="img",
        ),
    ]
