# Generated by Django 4.2.1 on 2023-05-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_imgfile_fileupload_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileupload",
            old_name="img",
            new_name="images",
        ),
    ]
