# Generated by Django 4.2.1 on 2023-05-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_img_fileupload_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileupload",
            old_name="images",
            new_name="imgfile",
        ),
    ]
