# Generated by Django 4.2.1 on 2023-05-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_filesave_imgfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesave",
            name="title",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
