# Generated by Django 4.2.1 on 2023-05-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_images_fileupload_imgfile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FileUpload",
            new_name="FileSave",
        ),
    ]
