# Generated by Django 4.2.1 on 2023-05-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_title_filesave_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesave",
            name="imgfile",
            field=models.ImageField(blank=True, null=True, upload_to="img"),
        ),
    ]
