# Generated by Django 4.2.1 on 2023-05-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_filesave_imgfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesave",
            name="filesize",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="filesave",
            name="filetype",
            field=models.TextField(null=True),
        ),
    ]
