# Generated by Django 4.2.1 on 2023-05-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_filesave_filetype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filesave",
            name="filetype",
        ),
    ]
