# Generated by Django 4.2.1 on 2023-05-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("home", "0010_remove_filesave_filetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesave",
            name="username",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="common.user"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="filesave",
            name="filename",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="filesave",
            table="home_filesave",
        ),
    ]
