# Generated by Django 4.2.1 on 2023-05-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_filesave_username_alter_filesave_filename_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filesave",
            old_name="username",
            new_name="user_id",
        ),
    ]
