# Generated by Django 4.2.1 on 2023-05-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fileup", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileupload",
            old_name="imgfile",
            new_name="file_imgfile",
        ),
        migrations.RenameField(
            model_name="fileupload",
            old_name="title",
            new_name="file_title",
        ),
    ]
